hub:
  baseUrl: "jupyterhub/"
  services:
    cscixxxx-assignments:
      url: http://host.k3d.internal:9000
      api_token: "7d9b94f7e7bab85e2b8fcb7c66bb20e74d009630f4be1ff1ec2f87865550357a"
      oauth_redirect_uri: http://k3d.local/jupyterhub/services/cscixxxx-assignments/auth.php
      oauth_no_confirm: True
  config:
    Authenticator:
      enable_auth_state: True
  loadRoles:
    user:
      scopes: ["access:services", "self"]
